/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ReadJSON;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReadJSONTaskTest {
    @Test public void testSomeLibraryMethod() 
    {
        ReadJSONTask classUnderTest = new ReadJSONTask();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.main(null));
    }
}
